### ISSUE TITLE
AQL error: [4] Cannot unlink root node of plan. (while optimizing plan)

### ISSUE THREAD

**Issue by baslr** [triAGENS/ArangoDB#1199]
This `FOR a IN test COLLECT foo = a.foo RETURN foo` works for my test collection but not for a collection that contains 78k docs created with a previous version of ArangoDB.

When I execute the query I get `[4] Cannot unlink root node of plan. (while optimizing plan)` This worked previously. I guess it was 2.3.1 / 2.3.2.

I exported and imported the collection into a testName collection. The execution of the query on this collection worked.

I run 2.3.3.

**Comment by jsteemann** [comment]
Thanks. I found that the issue had to do with the number and amount of indexes created for a collection. It may have occurred if there was a collection with more than one skiplist index on the attribute that was used in the `COLLECT` statement.
The issue has been fixed in 2.3.5, 2.4 and devel.
