### ISSUE TITLE
aardvark cant add Fulltext Index with multiple field names containing a  '.'

### ISSUE THREAD

**Issue by baslr** [triAGENS/ArangoDB#1201]
Request URL: http://192.168.178.22:8529/_db/_system/_api/index?collection=8570060254192

Request Payload:
{"type":"fulltext","fields":["test.pilot","rocket.master"],"minLength":0}

gives me

{"error":true,"code":400,"errorNum":10,"errorMessage":"bad parameter"}

The input in the webinterface is `test.pilot,rocket.master`

**Comment by jsteemann** [comment]
A fulltext index can only be created on a single attribute.
So even when specifying attribute names without a '.', the index will be created on a single attribute, and the index description (`fields`) attribute will also contain a single attribute only.
I'll check if there's too lax error checking if multiple attributes are specified.

**Comment by jsteemann** [comment]
Updated docs and added error checking.
