### ISSUE TITLE
Question about Foxx Model forClient

### ISSUE THREAD

**Issue by stackmagic** [triAGENS/ArangoDB#1205]
I am trying to get models working in the 2 cases I do queries.

In the first one, I get a unique object from the repository (trough byId or any) and can easily send it to the client with only the fields I have defined in the Model: `res.json( repository.any().forClient() );`

The second case is from a query that returns multiple results.

Repository:
```
findByLocation: Foxx.createQuery({"FOR x IN xs FILTER ... RETURN x"})
```

Now I found something with `_.map` [in the docs](https://docs.arangodb.com/cookbook/FoxxFirstSteps.html) but that doesn't seem to work when using a query. The example in the documentation uses `repository.all()`

Not calling `forClient()` returns too many fields but when I follow the sample from the documentation I get an error:

```
A runtime error occurred while executing an action: TypeError: undefined is not a function TypeError: undefined is not a function
``` 

... and the first line from the stacktrace points to the place I'm calling forClient()

Am I doing something wrong? How can I make `forClient` work in both cases?

**Comment by stackmagic** [comment]
> Keep in mind Foxx queries only return models if you pass the model option to Foxx.createQuery. Adding them to a repository is not enough.

Ah that's the trick! Thank you!

It makes sense having to explicitly setting the model because sometimes you may want to return something else than a model instance from your query.

**Comment by pekeler** [comment]
I just ran into a similar problem. Unless I'm missing something, Foxx.createQuery is not documented anywhere. This issue and the source are the only place to find out about the `model` option.

**Comment by pluma** [comment]
It's documented: https://docs.arangodb.com/Foxx/Develop/Queries.html

**Comment by pekeler** [comment]
Ah - thanks.
Using the search functionality on https://docs.arangodb.com to search for "createQuery" doesn't bring up anything.

**Comment by pluma** [comment]
Thanks for the heads up.

@13abylon Can you look into why `createQuery` isn't showing up in the search?
