### ISSUE TITLE
New website design

### ISSUE THREAD

**Issue by CoDEmanX** [triAGENS/ArangoDB#1207]
I like the new header, the key feature descriptions in multiple columns without icons not so much, but most importantly, there's an issue with the navigation bar:

![arango-broken-nav](https://cloud.githubusercontent.com/assets/1309249/5673459/9ba4ce86-979c-11e4-8654-b8dbe2ef4125.png)

It seems to be in the wrong place on all sub-pages.
(Firefox 34.0.5)

**Comment by fceller** [comment]
@CoDEmanX  Can you try a shift-reload? That solved the problem for me in Firefox.

**Comment by CoDEmanX** [comment]
Shift+F5 opens the Web console, Ctrl+F5 did the trick however - thanks!

**Comment by 13abylon** [comment]
Great, then this issue can be closed. Glad we could help :+1:

**Comment by CoDEmanX** [comment]
Found two more flaws on the re-arrangement website:

- **technical preview** link leads to Wordpress login form: https://www.arangodb.com/download
- **pdf** manual is listed twice, *epub* not once: https://www.arangodb.com/documentation

**Comment by 13abylon** [comment]
Thank you, both problems are fixed

**Comment by CoDEmanX** [comment]
Hm, I can't see **ePub**? The exists however: https://docs.arangodb.com/manual.epub

**Comment by 13abylon** [comment]
I think now it should be in again

**Comment by CoDEmanX** [comment]
One more thing: I really miss the icons on the [documentation page](https://www.arangodb.com/documentation). Did you remove them on purpose?

They gave the page a delightful look, and wasn't as overloaded with information as the new page.
