### ISSUE TITLE
Arango 2.3 / 2.4 beta online documentation

### ISSUE THREAD

**Issue by CoDEmanX** [triAGENS/ArangoDB#1209]
The search feature is broken in both versions, if you enter e.g. *aql*, nothing is found.

It would be nice to have the same links like on the [documentation page](https://www.arangodb.com/documentation) to download PDF / ePUB / MOBI version of the documentation, should be above or below "Have any issues? Have any questions?"

**Comment by 13abylon** [comment]
1. Broken Search:
Which browser are you using? 

2. We will discuss about adding pdf/mobi/epub to the documentation page to download from. Thanks for the idea

**Comment by CoDEmanX** [comment]
I'm using Firefox 34.0.5

**Comment by 13abylon** [comment]
I can't confirm that bug. I've tried it with `Firefox 34.0.0` with `OS X 10.10.1` and the search feature is working fine.

Have you tried a shift reload?

**Comment by CoDEmanX** [comment]
Went to private mode, did a full reload and still broken on Windows 8, no errors in web console.

**Comment by fceller** [comment]
@13abylon We have a Windows 8 machine you can use for tests. Ask Willi

**Comment by CoDEmanX** [comment]
@13abylon: Did you change anything in last couple minutes? It works ATM, there "x" is still not showing however.

**Comment by 13abylon** [comment]
No, i did nothing at the documentation. 
The "x" is not in the documentation at the moment, we had some troubles with it. 
I will try to fix this in the next few days

**Comment by 13abylon** [comment]
Does it still work in firefox? If yes, I would like to close this issue

**Comment by CoDEmanX** [comment]
Yes, it does...

I found another issue with the search however: type in something like `asd`, nothing is found. Click on the magnifier icon to close search, all items return. Click on the magnifier icon again, search field shows up again and has nothing entered. Now click any item - the previous search phrase suddenly re-appears.

**Comment by 13abylon** [comment]
Yes, this is a bug from gitbook I hope they will fix soon :)
