### ISSUE TITLE
Query general graph for common neighbors with more than 2 vertices?

### ISSUE THREAD

**Issue by CoDEmanX** [triAGENS/ArangoDB#1210]
Consider the following example graph:

![multivert_commonneighbors](https://cloud.githubusercontent.com/assets/1309249/5720916/2bf9a6b4-9b2b-11e4-8e83-721d6a7e1f30.png)

1. Given the vertices A, B and C (creators), how to figure out their common neighbors (projects all 3 participated in)? For two vertices, I could simply use `GRAPH_COMMON_NEIGHBORS("myGraph", A, B)`, but what if I want to query for 3 or more? Expected result: 1 and 2.

2. Given the same vertices, how can I make it return common neighbors with no other connections (creators exclusively participated in a project, no additional edges allowed)? Expected result: 1, because 2 has an edge coming from D, which isn't one of the starting vertices.

(BTW: should I post such questions on stackoverflow instead?)

**Comment by CoDEmanX** [comment]
I believe I solved it after some sketches on paper:

1. Get edges of all start vertices `GRAPH_EDGES() `, get the INTERSECTION () of the `_to` edge attribute and get the target vertices by these IDs

2. basically same as above, but get all edges of target vertices going to start vertices to count their number. If number of edges is equal to number of start vertices, then target vertices can only be linked by either of the start vertices (granted there are no duplicate edges and direction is checked if there could be edges going back from target to start vertices)

**Comment by mchacki** [comment]
Hi @CoDEmanX i think your solutions will also work, but you can do it with COMMON_NEIGHBROS only:

    let res = (for x in (
      let nodes =  ["a/A","a/B","a/C"]
      for n in GRAPH_COMMON_NEIGHBORS("g",nodes , nodes) 
        for f in VALUES(n)
          return VALUES(f)
    ) return x)
    return CALL("intersection", res[0])

Nodes is the list of vertices where you would like to find common neighbors for.
Giving a list of vertices as parameters will compute neighbors of all distinct combinations of vertices in both sets. As a final step we extract the intersection of these neighbors to find only the ones connected to all pairs.

**Comment by mchacki** [comment]
Ah and according to your btw: i think this is actually a question suitable for Stackoverflow. It is not a real issue.

**Comment by CoDEmanX** [comment]
Many thanks, mchacki! I didn't realize you could pass a list of nodes to graph functions.

In terms of efficiency (memory and cpu-wise), which approach do you think is better? In a rather large graph, could be the intermediate result of your solution require more memory? Is `intersection()` optimized in some way? (start with smallest set...)

Put the question up on SO for you to copy your answer over: http://stackoverflow.com/questions/27939423/query-arangodb-general-graph-for-common-neighbors-with-more-than-2-start-vertice

**Comment by mchacki** [comment]
I think we can close it now.
