### ISSUE TITLE
Can't download generated App

### ISSUE THREAD

**Issue by tbo** [triAGENS/ArangoDB#1215]
I installed ArangoDB 2.4 with homebrew on Mac OS 10.10.1 and followed the "Foxx in 10 minutes" tutorial. Unfortunately I was not able to download the newly generated app. Instead an empty browser tab opened (loading indicator active) and my ArangoDBs CPU usage rose to 60%.

I checked the log, but everything seemed normal. I reinstalled ArangoDB (this time I downloaded it from the homepage) and tried it several times. The result was always the same, with one exception: I wasn't able to choose an application name more than once. If I name the app "firstApp" again and press "generate" nothing happens.

Tracing level log file:
https://gist.github.com/tbo/48424a49533ba60d5893

**Comment by bachp** [comment]
I observe similar behaviour on Windows 8.1 and ArangoDB 2.4.0 64-bit

The difference is that when I try to download a generated app ``arangod.exe`` crashes.
Logs with ``level = debug`` shows nothing special.

**Comment by fceller** [comment]
We will release 2.4.1 tomorrow which fixes this bug.

**Comment by bachp** [comment]
Perfect. So no need to investigate further from my side ;)
Thanks for letting us know.

**Comment by fceller** [comment]
Please test 2.4.1.

**Comment by bachp** [comment]
Just tested with 2.4.1 on Windows 8.1 64bit and it is working now. Thanks.
