### ISSUE TITLE
/_api/replication/logger-state clients field

### ISSUE THREAD

**Issue by stackmagic** [triAGENS/ArangoDB#1219]
The endpoint `/_api/replication/logger-state` returns a field `clients` which is an empty list in my case and [the documentation](https://docs.arangodb.com/HttpReplications/ReplicationLogger.html) doesn't mention this field at all. 

Could you add some documentation for this field please? I assume it's safe to just ignore whatever this field contains.

**Comment by jsteemann** [comment]
Thanks for the hint. I have updated the code comments accordingly, which are used for documentation generation.
At the moment the *clients* attribute will be an empty list in all cases, so it is safe to ignore.

**Comment by stackmagic** [comment]
Perfect, Thanks!
