### ISSUE TITLE
Create a best practices document for querying

### ISSUE THREAD

**Issue by jsteemann** [triAGENS/ArangoDB#784]
It would make sense to compile an overview of best practices for querying data from ArangoDB, maybe with a few examples how to implement specific use cases best with ArangoDB.
This has been requested a few times now. Latest request was:

> Is there a document with tips and tricks when using arangoDB? Something like Dos&Donts or some other "I've learned it the hard way" document.

**Comment by 13abylon** [comment]
We now have a cookbook where we have an overview of problems and solutions. It is also kind of a how to for specific use cases in ArangoDB.
If there is something missing, you can write a recipe: https://docs.arangodb.com/cookbook
